name: Deploy Golang Docs App

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "PORT=${{ secrets.PORT }}" > .env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the image
        run: docker build -t fenilpanseriya/docs:latest .

      - name: Push the image
        run: docker push fenilpanseriya/docs:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - name: Clean up unused containers, images, and volumes
      run: |
        echo "Stopping and removing old containers..."
        sudo docker-compose down --volumes --remove-orphans || true
        echo "Removing dangling images..."
        sudo docker image prune -af
        echo "Removing unused volumes..."
        sudo docker volume prune -f

    - name: Pull the new image
      run: sudo docker pull fenilpanseriya/docs:latest
    - name: Create .env file
      run: |
        echo "PORT=${{ secrets.PORT }}" > .env
        echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
    - name: Print current directory
      run: |
        pwd
        ls -al
        
    - name: Start containers with docker-compose
      run: sudo docker-compose up
      
