name: Deploy golan docs app
on:
  push:
    branches:
     - main
jobs:
    build:
      name: build the image
      runs-on: ubuntu-latest
      steps:
        - name: checkout sources
          uses: actions/checkout@v4
        - name: create .env file
          run: echo "PORT=${{ secrets.PORT }}" > .env
        - name: login into dockerhub
          run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        - name: build the image
          run: docker build -t fenilpanseriya/docs:latest .
        - name: push the image
          run: docker push fenilpanseriya/docs:latest
    deploy:
      needs: build
      runs-on: self-hosted
      steps:
        - name: pull the docker image
          run: docker pull fenilpanseriya/docs:latest
        - name: stop the old container
          run: docker rm -f docs
        - name: run the new container
          run: docker run -d --name docs -p ${{ secrets.PORT }}:${{ secrets.PORT }} fenilpanseriya/docs:latest
    
    